apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "routify.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "routify.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      {{- include "routify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin
  template:
    metadata:
      labels:
        {{- include "routify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.admin.env.apiUrl | quote }}
            - name: ROUTIFY_ENV_VAR_GOOGLE_CLIENT_ID
              value: {{ .Values.admin.env.googleClientId | quote }}
            - name: ROUTIFY_ENV_VAR_API_URL
              value: {{ .Values.admin.env.apiUrl | quote }}