apiVersion: v1
kind: Service
metadata:
  name: {{ include "routify.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "routify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "routify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin