apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "routify.fullname" . }}-configmap
  labels:
    {{- include "routify.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.environment }}
  DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
  REACT_APP_API_URL: {{ .Values.frontend.env.apiUrl | quote }}