apiVersion: v1
kind: Service
metadata:
  name: {{ include "routify.fullname" . }}-gateway
  labels:
    {{- include "routify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "routify.name" . }}
    tier: gateway
