apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "routify.fullname" . }}-gateway
  labels:
    {{- include "routify.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "routify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "routify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "routify.fullname" . }}-configmap
            - secretRef:
                name: {{ include "routify.fullname" . }}-secret
          env:
            - name: Api__Token
              valueFrom:
                secretKeyRef:
                  name: {{ include "routify.fullname" . }}-secret
                  key: GATEWAY_TOKEN
            - name: Api__BaseUrl
              value: "http://{{ include "routify.fullname" . }}-api:{{ .Values.api.service.port }}"
            - name: Redis__ConnectionString
              value: "{{ include "routify.redisHost" . }}:{{ include "routify.redisPort" . }}"