apiVersion: v1
kind: Secret
metadata:
  name: {{ include "routify.fullname" . }}-secret
  labels:
    {{- include "routify.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.api.jwt.secret | b64enc }}
  JWT_ISSUER: {{ .Values.api.jwt.issuer | b64enc }}
  JWT_AUDIENCE: {{ .Values.api.jwt.audience | b64enc }}
  GATEWAY_TOKEN: {{ .Values.api.gateway.token | b64enc }}
  ENCRYPTION_KEY: {{ .Values.api.encryption.key | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.frontend.env.googleClientId | b64enc }}